### ISSUE TITLE
No Type hinting for openpyxl.utils.escape module

### ISSUE THREAD

**Issue by dod-wdwilcox** [MartinThoma/openpyxl-stubs#10]
from mypy after installing: error: Skipping analyzing 'openpyxl.utils.escape': found module but no type hints or library stubs

**Comment by dod-wdwilcox** [comment]
I have a feature branch ready to submit a PR for this.
```ERROR: Permission to MartinThoma/openpyxl-stubs.git denied to dod-wdwilcox.```

**Comment by MartinThoma** [comment]
This was closed by your PR - thank you :hugs:
