### ISSUE TITLE
Issue on openpyxl.reader.excel

### ISSUE THREAD

**Issue by eric-bonfadini** [MartinThoma/openpyxl-stubs#15]
I'm using 

```
mypy==0.910
```
```
openpyxl==3.0.7
openpyxl-stubs==0.1.19
```
and I'm getting this error:
`error: Skipping analyzing "openpyxl.reader.excel": found module but no type hints or library stubs`

when I call mypy on this sample file:

```
from openpyxl import Workbook
from openpyxl.cell import Cell
from openpyxl.styles import PatternFill, Border, Alignment, Font, Side
from openpyxl.styles.colors import Color
from openpyxl.reader.excel import load_workbook
```

Can it be because of a missing `__init__.pyi` inside reader module?

**Comment by MartinThoma** [comment]
@eric-bonfadini Thank you for the hint! Yes, the `__init__.pyi` was missing (also in another module). I've added it :-)
