### ISSUE TITLE
Allow Cell.value to be float

### ISSUE THREAD

**Issue by robertmetcalf** [MartinThoma/openpyxl-stubs#19]
In file `cell/cell.pyi`, the `Cell()` class defines

- `value: Optional[Union[datetime.date, str, int]] = ...,`

Consider adding float as a type.

- `value: Optional[Union[datetime.date, str, int, float]] = ...,`

See the documentation for [openpyxl.cell.cell module](https://openpyxl.readthedocs.io/en/stable/api/openpyxl.cell.cell.html).

**Comment by MartinThoma** [comment]
If you add a pr, I'll accept it :-)
