### ISSUE TITLE
Workbook has no attribute "defined_names"

### ISSUE THREAD

**Issue by danvk** [MartinThoma/openpyxl-stubs#23]
The openpyxl docs for [Workbook](https://openpyxl.readthedocs.io/en/stable/api/openpyxl.workbook.workbook.html?highlight=workbook) mention `Workbook.defined_names` a few times (`add_named_range` and a few other methods are deprecated in favor of `defined_names`) but this property is missing from the openpyxl stubs.

**Comment by MartinThoma** [comment]
I'm open to PRs 😇

**Comment by MartinThoma** [comment]
`0.1.25` was just released with this fix
